version: '3'
services:
  postgresdb:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}      
    ports:
      - "1234:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - digital-bank  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgresdb
  api:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
      args:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    networks:
      - digital-bank
    restart: on-failure

networks:
  digital-bank:
    driver: bridge